# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.show-sql=true
# spring.datasource.url=jdbc:postgresql://db.rlmqejnjuahvcuoqowpz.supabase.co:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=Gjgdsjhgkhk.6696
# spring.datasource.initialization-mode=always
# spring.datasource.initialize=true
# spring.datasource.continue-on-error=true
# spring.jpa.hibernate.ddl-auto=create-drop
#     server.port=8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: darkhunter23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port : 8081